config:
  github:owner: davidasnider
  github-management:repository_name: home-agent-suite
  github-management:protected_branch: main
  github-management:required_reviews: "1"
  github-management:dismiss_stale_reviews: "true"
  github-management:require_code_owner_reviews: "false"
  github-management:allow_review_dismissals: "true"
  github-management:restrict_pushes: []
  github-management:allow_force_pushes: "false"
  github-management:allow_deletions: "false"
  github-management:require_status_checks: "true"
  github-management:require_up_to_date: "true"
  github-management:enforce_admins: "true"
  github-management:status_check_contexts:
    - "Code Formatting"
    - "Code Linting"
    - "Unit Tests (Day Planner)"
    - "Unit Tests (Google Search Agent)"
    - "Unit Tests (Supervisor)"
    - "Unit Tests (Common Logging)"
    - "Unit Tests (Tomorrow.io Client)"
  github-management:delete_branch_on_merge: "true"
