repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files


-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.90.8
    hooks:
    -   id: trufflehog
        args: [--only-verified]

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
    -   id: detect-secrets
        name: detect-secrets
        entry: poetry run detect-secrets-hook
        args: ["--baseline", ".secrets.baseline"]
        language: system
        types: [text]
    -   id: pytest-coverage
        name: pytest-coverage
        entry: poetry run pytest --cov=. --cov-fail-under=86 --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
