repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
    -   id: gitleaks

-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.80.0
    hooks:
    -   id: trufflehog
        args: [--only-verified]

-   repo: local
    hooks:
    -   id: pytest-coverage
        name: pytest-coverage
        entry: poetry run pytest --cov=. --cov-fail-under=86 --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
