"I found some excellent restaurant "
                                "recommendations for Paris! Here are the top "
                                "results:\n\n1. **Best Restaurants in Paris - "
                                "Travel Guide**: Discover the finest dining "
                                "experiences in Paris, from Michelin-starred "
                                "establishments to cozy bistros.\n\n2. **Top 10 "
                                "Must-Try Restaurants in Paris**: A curated list of "
                                "exceptional restaurants in the City of Light."
