name: CI & Quality Checks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    name: Code Quality and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Load cached virtual environment
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies for all projects
        run: |
          # Install root dependencies first (contains black, flake8, pytest)
          poetry install --no-interaction
          # Install dependencies for all sub-projects to ensure path dependencies are available
          find . -path "./agents/*" -name pyproject.toml -execdir poetry install --no-interaction \;
          find . -path "./libs/*" -name pyproject.toml -execdir poetry install --no-interaction \;
      - name: Check Formatting with Black
        run: poetry run black . --check
      - name: Lint with Flake8
        run: poetry run flake8 .
      - name: Run Unit Tests
        run: poetry run pytest
